---
services:
  frontend:
    image: todo-frontend-dev
    container_name: todo-frontend-dev
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
    volumes:
      - ./todo-frontend:/usr/src/app
  nginx:
    image: nginx:1.21
    container_name: todo-nginx-dev
    ports:
      - "127.0.0.1:80:80"
    links:
      - frontend
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
