---
services:
  backend:
    image: todo-backend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: todo-backend-dev
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - REDIS_URL=redis://redis:6379
    links:
      - mongo
      - redis
    volumes:
      - .:/usr/src/app
    tty:
      true
  mongo:
    image: mongo
    container_name: todo-mongo-dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo_data:/data/db
  redis:
    image: redis
    container_name: todo-redis-dev
    command: redis-server --appendonly yes
    volumes:
      - ./redis_data:/data
