---
services:
  frontend:
    image: node:20
    container_name: todo-frontend-dev
    working_dir: /usr/src/app
    entrypoint: npm run dev --  --host
    volumes:
      - .:/usr/src/app
    ports:
      - "127.0.0.1:5173:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
    tty: true
